version: '3.4'

services:
  s_apigateway:
    container_name: c_apigateway
    image: omereryilmaz/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 80:80

  s_contact_api:
    container_name: c_contact_api
    image: omereryilmaz/contactapi
    build:
      context: .
      dockerfile: Services/Contact/Contact.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9001:9001

  s_res_api:
    container_name: c_res_api
    image: omereryilmaz/resapi
    build:
      context: .
      dockerfile: Services/Reservation/Reservation.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9002:9002


networks:
  net_api:
    driver: bridge

  int_net_api:
    driver: overlay
    internal: true